# Generated by Django 3.2.2 on 2021-05-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='electricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='neumaticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
